name: test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: src/github.com/k14s/k14s.io
    - name: Run Tests
      run: |
        set -e -x
        # install ytt for build
        mkdir -p tmp/bin/
        cat ./pkg/website/templates/install.sh | K14SIO_INSTALL_BIN_DIR=tmp/bin bash
        export PATH=`pwd`/tmp/bin:$PATH
        export GOPATH=$(echo `pwd`)
        cd src/github.com/k14s/k14s.io
        ./hack/build.sh
        ./hack/test.sh
